sudo: false
language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - DB_USER=wp
    - DB_PASSWORD=password
    - DB_NAME=wp_tests

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

before_script:
  - mysql -u root -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO ${DB_USER} IDENTIFIED BY '${DB_PASSWORD}';"
  - mysql -u root -e "CREATE DATABASE ${DB_NAME};"

script:
  - composer lint
  - composer test
